config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out



 	 resources :tapes do
 	 	resources :songs
 	 end
end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
	# belongs_to :user
	# has_many :songs

 # has_attached_file :song
 # validates_attachment_presence :song
 # validates_attachment_content_type :song, :content_type => [ 'audio/mp3','audio/mpeg']
end

app/models/song.rb
class Song < ActiveRecord::Base
     belongs_to :tape
     belongs_to :user, class_name: :user, foreign_key: :user_id
	 has_attached_file :song,
	 					:path => ":rails_root/app/assets/audios/:filename",
	 					:url  => "/songs/:id/:filename",
	 					:default_url => "/assets/audios"


	 validates :tape, presence: true
	 validates_attachment_presence :song
	 validates_attachment_content_type :song, :content_type => [ 'audio/mp3','audio/mpeg']
	 validates_attachment_size :song, :less_than => 10.megabytes, 
	    :message => 'filesize must be less than 10 MegaBytes' 
end

app/models/tape.rb
class Tape < ActiveRecord::Base
	belongs_to :user
	has_many :songs, dependent: :destroy
	
	validates :description,  length: { maximum: 1000 }
	validates :tapename,  length: { maximum: 20 }
	validates_presence_of :tapename, :description, :tapepic

	has_attached_file :tapepic, styles: { medium: "200x200#", thumb: "100x100#" }, :default_url => ActionController::Base.helpers.asset_path('purple_tape.jpg')	
	validates_attachment_content_type :tapepic, content_type: /\Aimage\/.*\Z/
	
	# validate :songs_limit, :on => :create

	#   private
	#   def songs_limit
	#     return if songs.blank?
	#     errors.add("You have reached the song limit") if songs.length > 8
	#   end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tapes, dependent: :destroy
	has_many :songs
	
  	# validates :avatar, attachment_presence: true

	attr_accessor :password_salt
	attr_accessor :password_hash
	
	before_validation :normalize_username, on: :createi
	before_save :encrypt_password

	has_attached_file :avatar, styles: { medium: "200x200#", thumb: "100x100#" }, :default_url => ActionController::Base.helpers.asset_path('pink_tape.jpg')	
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  	validates_uniqueness_of :username
	validates :password, confirmation: true, presence: true, length: { minimum: 5 }
	validates :username, presence: true, length: { maximum: 15 }
	validates_presence_of :username, :fname, :lname, :password, :avatar

	protected
		 def encrypt_password
		 	  if password.present?
	     		 self.password_salt = BCrypt::Engine.generate_salt
	     		 self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	 		 end
		 end

		 def normalize_username
	      self.username = self.username.downcase
	    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
		helper_method :current_user
	end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
      if @user && @user.password == params[:password]
        session[:user_id] = @user.id
        flash[:notice] = "Success."
        redirect_to @user
      else
        flash[:alert] = "Wrong credentials. Please try again"
        render :new
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out."
    redirect_to root_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    @tape = Tape.find(params[:tape_id])
    @song = @tape.songs.create(song_params)
    @song.user_id = current_user.id

    if @song.save
      flash[:heya] = "Song added"
    else
      flash[:notworking] = "Song not added"
    end
    redirect_to @tape
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @song.destroy
    redirect_to tapes_path
  end

  private

  def song_params
    params.require(:song).permit(:song)
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  before_action :set_tape, only: [:show, :edit, :update, :destroy]

  def index
    @tapes = Tape.all
  end

  def new
    @tape = Tape.new
    @song = Song.new
  end

  def create
    @tape = Tape.create(tape_params)
    @tape.user_id = session[:user_id]
    if @tape.save
      redirect_to tape_path(@tape.id)
    else
      redirect_to new_tape_path(current_user)
      flash[:notape] = "Please keep your tape name and description short. And remember to add an image"
    end
  end

  def show
    @tapes = Tape.all
  end

  def edit
  end

  def update
    if @tape.update(tape_params)
      @tape.user_id = params[:user_id]
      redirect_to [@tape.user, @tape]
    end
  end

  def destroy
    @tape.destroy
    redirect_to user_path(current_user)
  end

  private

  def tape_params
    params.require(:tape).permit(:tapename, :description, :user_id, :tapepic).merge(user: current_user)
  end

  def song_params
    params.require(:song).permit(:songs)
  end

  def set_tape
    @tape = Tape.find(params[:id])
    @songs = @tape.songs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id #VERY IMPORTANT, LIKE SERIOUSLY
      flash[:created] = "New user created"
      redirect_to @user
    else
      flash[:fillagain] = "Please fill the form correctly"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to log_in_path
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:fname, :lname, :username, :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	:current_user
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- HOME WRAPPER -->
<div id="home_wrapper">
   <a href="/"><%= image_tag "logo_bw.png", class: :logo %></a>
   <!-- HOME NAVBAR -->
   <nav>
      <ul>
         <li><a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official fa-2x"></i></a></li>
         <li><a href="http://www.soundcloud.com" target="_blank"><i class="fa fa-soundcloud fa-2x"></i></a></li>
         <li><a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter fa-2x"></i></a></li>
         <li><a href="http://www.tumblr.com" target="_blank"><i class="fa fa-tumblr fa-2x"></i></a></li>
      </ul>
   </nav>
   <button class="home-btn">
      <a class="whitelinks" href="/users/new">
         <h2>START HERE</h2>
      </a>
   </button>
   <!-- HOMEPAGE FOOTER © -->
   <footer>
      <hr>
      <h6>created by Joe Gigs & Jose Plata</h6>
   </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mixt | Share Mixtapes</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/wow/0.1.12/wow.min.js'></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- FONT AWESOME ICONS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- GOOGLE FONTS -->
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,700,300,300italic' rel='stylesheet' type='text/css'>
    <!-- JPLAYER SCRIPT -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>
  <body>
    <%= yield %>
    <!-- jquery -->
    <script>
      $('#toggle').click(function() {
            $(this).toggleClass('active');
            $('#overlay').toggleClass('open');
           });
    </script>
  </body>
</html>

app/views/tapes/_form.html.erb
<div class="all_wrapper">
<%=  link_to(image_tag("logo_pink.png", size:"120x49"), user_path(current_user), class: :logo) %>
	<!--  NAVBAR -->
	<nav class="all_nav">
		<ul>
			<li><a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a></li>
			<li><a href="http://www.soundcloud.com" target="_blank"><i class="fa fa-soundcloud"></i></a></li>
			<li><a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></li>
			<li><a href="http://www.tumblr.com" target="_blank"><i class="fa fa-tumblr"></i></a></li>
		</ul>
	</nav>
	
	<%= form_for @tape do |tape| %> 
		<div class="newtape">
			<h2><%= tape.text_field :tapename, class: :tape_form, :placeholder => "Tape Name (short)" %></h2><br><br>
			<h1 style="color: black ; text-transform: uppercase; font-size: 12px"> Add an image here </h1><br>
			<%= tape.file_field :tapepic, :placeholder => "Add an image" %><br><br>
			<h2><%= tape.text_area :description, id: :description, :placeholder => "Leave a message here. Please keep it under 1000 characters" %></h2><br><br>
			
			<div id="songs">
				<br><br>
				<%= tape.submit 'Create Tape', class: :create_button %>
				<br><br>
				<%= link_to "Go Back" , user_path(current_user), :class => :create_button %>
				<br><br>
				<h2 style="color: black"><%= flash[:notape] if flash[:notape] %></h2>
			</div>
		</div>

	<% end %>
</div>
​
<div class="all_footer">
	<hr><br>
	<span class="copyright">&copy; Mixt</span>
</div>
​

app/views/tapes/_index.html.erb
<% if current_user %>
	<% @user.tapes.each do |tape| %>
			<%= link_to image_tag(tape.tapepic.url(:medium)), tape_path(tape.id) %>
	<% end %>
<% end %>

app/views/tapes/new.html.erb
<%= render 'form' %>

app/views/tapes/show.html.erb
<div class="tape_page_wrapper">
	
	<%=  link_to(image_tag("logo_pink.png", size:"120x49"), user_path(current_user), class: :logo) %>

	<!--  NAVBAR -->
	<nav class="all_nav_tape">
		<ul>
			<li><a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a></li>
			<li><a href="http://www.soundcloud.com" target="_blank"><i class="fa fa-soundcloud"></i></a></li>
			<li><a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></li>
			<li><a href="http://www.tumblr.com" target="_blank"><i class="fa fa-tumblr"></i></a></li>
		</ul>
	</nav>
	
	<div id="add_song">
		<%= form_for([@tape, Song.new]) do |song| %>
		<!-- HOPEFULLY THIS WOULD WORK -->
			<%= song.file_field :song %><br>
			<%= song.submit 'ADD A SONG', :class => 'submit_button_small' %>
		<% end %> 

		<h2><%= flash[:notworking] if flash[:notworking] %></h2>
		<h2><%= flash[:heya] if flash[:heya] %></h2>
	 </div>

	<div id="tape_page_for_user">
		<h2><%= @tape.tapename %></h2>
		<hr>
	</div>

	<div class="tapes_avatar">
		<%= image_tag @tape.tapepic.url(:medium) %>
	</div>

	<div id="tape_player_controls">
		<% @songs.each do |song| %>
			<h2><%= audio_tag(song.song_file_name, autoplay: false, controls: true, :class => :audiotags) %></h2>
		<% end %>
	</div>

	<div id="tracklist_list">
			<ul id="listofsongs">
				<% @songs.each do |song| %>
				  <h5><li><%= song.song_file_name %></li></h5>
				<% end %>
			</ul>
	</div>
	<br><br>
	<div id="message_block">
		<h3><%= @tape.description %></h3><br><br>

		<h3 style="text-align: center ; color: white ; display: inline"><%= link_to "Go Back" , user_path(current_user), :class => :create_button %></h3>
		<h3 style="text-align: center ; color: white ; display: inline"><%= link_to "Delete Tape", tape_path, data: { confirm: "are you sure? "}, method: :delete, class: :create_button %></h3>

	</div>
</div>

<!-- POPUP LINK -->
<div class="button_container" id="toggle">
	<h1>SHARE</h1>
	<br>
	<span class="top"></span>
  	<span class="middle"></span>
  	<span class="bottom"></span>
</div>

<div class="overlay" id="overlay">
  <div class="overlay-menu">
    <ul>
      <p>All set! Copy the following link<br>to share your mixtape</p>
      <br>
      <div id="link_tape_box">
	  <li><a href="" class="link_for_tape"><%= tape_url %></a></li></div>
      <br><br>
      <li><a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a></li>
	  <li><a href="http://www.soundcloud.com" target="_blank"><i class="fa fa-soundcloud"></i></a></li>
      <li><a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></li>
	  <li><a href="http://www.tumblr.com" target="_blank"><i class="fa fa-tumblr"></i></a></li>
    </ul>
  </div>
</div>

<!-- end of popup -->

<div class="tape_page_footer">
	<hr><br>
	<span class="copyright">&copy; Mixt</span>
</div>

app/views/users/_form.html.erb
<div class="user_form">
<h3><%= flash[:fillagain] if flash[:fillagain] %></h3>

	<%= form_for @user do |user|%>
		
		<div class="form">
			<%= user.text_field :fname, class: :form_fields, :placeholder => "First Name" %> <br><br>
			<%= user.text_field :lname, class: :form_fields, :placeholder => "Last Name" %> <br><br>
			<%= user.text_field :username, class: :form_fields, :placeholder => "Username"  %> <br><br>
			<%= user.password_field :password, class: :form_fields, :placeholder => "Password"  %> <br><br>
			<%= user.password_field :password_confirmation, class: :form_fields, :placeholder => "Confirm Password"  %> 
			<br><br>
			<%= user.file_field :avatar, :class => 'file_field' %>
		</div>
		<div class="submits">
		<%= user.submit 'CREATE MIXT ACCOUNT', :class => 'submit_button'  %>
		</div>
	<% end %>
</div>

app/views/users/new.html.erb
<div id="full_grad">
		<a href="/"><%= image_tag "logo_blue.png", class: :logo %></a>

		<!-- HOME NAVBAR -->
		<nav>
			<ul>
				<li><a href=""><i class="fa fa-facebook-official"></i></a></li>
				<li><a href=""><i class="fa fa-soundcloud"></i></a></li>
				<li><a href=""><i class="fa fa-twitter"></i></a></li>
				<li><a href=""><i class="fa fa-tumblr"></i></a></li>
			</ul>
		</nav>

		<!-- MAIN FORM -->
		<div id="sign_wrap">
			<div class="centered-text">
				<h2>CREATE YOUR FREE ACCOUNT</h2>
			</div>
			
			<%= render 'form' %>
		
			<h3>ALREADY HAVE AN ACCOUNT? <a href="/log-in"><strong>SIGN IN</strong></a></h3>

		</div>
		
		<!-- SIGNUP/SIGNIN FOOTER -->
		<div class="terms">
			<ul>
				<li><h5>FORGOT PASSWORD? • </h5></li>
				<li><h5>PRIVACY POLICY • </h5></li>
				<li><h5>CONTACT</h5></li>
			</ul>
		</div>
</div>


 

app/views/users/show.html.erb
<div class="all_wrapper">
<%=  link_to(image_tag("logo_pink.png", size:"120x49"), user_path(current_user), class: :logo) %>

	<!--  NAVBAR -->
	<nav class="all_nav">
		<ul>
			<li><a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a></li>
			<li><a href="http://www.soundcloud.com" target="_blank"><i class="fa fa-soundcloud"></i></a></li>
			<li><a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></li>
			<li><a href="http://www.tumblr.com" target="_blank"><i class="fa fa-tumblr"></i></a></li>
		</ul>
	</nav>

	<div id="prof_info">
		<h2><%= @user.fname + " " + @user.lname %></h2>
		<hr>
		<span class="prof_pic"><%= image_tag @user.avatar.url(:medium) %></span>
		<div class="tapes_shared"><h2><%= @user.tapes.count %> tapes shared</h2></div>
		<p><%= flash[:created] if flash[:created] %></p>
	</div>

<% if current_user %>
	<div id="to_mixtape">
		<%= link_to "create new mixtape", new_tape_path, class: :create_button %>
	</div>

	<div id="sign_out">
		<%= link_to "sign out", log_out_path %>
	</div>
<% end %>


	<div id="tapelist">
		<h2>YOUR MIXTAPES</h2>
		<hr>
		
		<%= render 'tapes/index' %>

	</div>


</div>

<div class="all_footer">
	<hr><br>
	<span class="copyright">&copy; Mixt</span>
</div>